baseURL = "https://yuzu-pri.github.io/mhrise-introduction-cards"
languageCode = "ja"
title = "Monster Hunter Rise 自己紹介カード (HN: YUZU)"
disableKinds = ["RSS", "sitemap"]
theme = "ananke"
publishDir = "docs"

[taxonomies]
tag = "tags"

